### PR TITLE
Bumps version

### PR DESCRIPTION
**Pull request by Adamits**
New release fixing transformer bug.

### CODE REVIEW

**Comment by kylebgorman** [comment]
LGTM. Do you have the permissions needed to create a release and upload to PyPI? (Docs at the bottom of the README.)

**Comment by Adamits** [comment]
I don't see an option on the github interface, but I can try to tag and push from my terminal.

**Comment by Adamits** [comment]
Just realized I am being silly -- I tagged my fork lol. I don't think I can 'merge' a tag?

**Comment by kylebgorman** [comment]
Tags · CUNY-CL/yoyodynegithub.comTry here…On Oct 20, 2023, at 9:56 AM, Adam ***@***.***> wrote:﻿
Just realized I am being silly -- I tagged my fork lol. I don't think I can 'merge' a tag?

**Comment by Adamits** [comment]
Hey Kyle,

Whatever you linked seems to not have formatted correctly. But I may have confused you. Typically there is an option to make a new release, but I do not have that with this yoyodyne in your CUNY-CL user. I thought maybe I can do this from the terminal with a tag, but forgot that locally I only have my own fork, so I don't think that does anything for us.

I assume only you have access to release.

**Comment by kylebgorman** [comment]
I’ll work on it, np. Traveling, so give me a few days.On Oct 20, 2023, at 11:51 AM, Adam ***@***.***> wrote:﻿
Hey Kyle,
Whatever you linked seems to not have formatted correctly. But I may have confused you. Typically there is an option to make a new release, but I do not have that with this yoyodyne in your CUNY-CL user. I thought maybe I can do this from the terminal with a tag, but forgot that locally I only have my own fork, so I don't think that does anything for us.
I assume only you have access to release.

**Comment by Adamits** [comment]
Sounds good, enjoy your travel.

**Comment by kylebgorman** [comment]
Done BTW.

**Pull request merged**
