### PR TITLE
Updates new evaluators code to work with Transducer.

### PR DESCRIPTION
**Pull request by Adamits**
I guess I had forgotten to test the Transducer with this change---it break since it has already "finalized" the prediction tensors. This fixes that by allowing for finalized predictions.

### CODE REVIEW

**Comment by Adamits** [comment]
Also @kylebgorman I cannot remember what our convention is---do you need me to create an issue to link this to?

**Comment by kylebgorman** [comment]
> Also @kylebgorman I cannot remember what our convention is---do you need me to create an issue to link this to?

Not strictly necessary, no.

**Review by kylebgorman — APPROVED** [review]
LGTM. I had to do a manual merge in `transducers.py`: could you visually inspect before I merge this into master?

**Comment by Adamits** [comment]
@kylebgorman I am not able to see the merge code? Or should I be looking at the other PR?

**Comment by kylebgorman** [comment]
> @kylebgorman I am not able to see the merge code? Or should I be looking at the other PR?

Just look at files changed on the right tab.

**Comment by Adamits** [comment]
I only see my changes +your small changes to my comments. When I click the merge commit I see this:

Screenshot 2024-06-13 at 7 27 55 PM

**Comment by kylebgorman** [comment]
I'm just going to merge.

**Pull request merged**
