### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kylebgorman**
This doesn't work so I'm removing the reference to it.

### CODE REVIEW

**Comment by Adamits** [comment]
I am fairly certain that I tested it in several setups for all architectures in this PR https://github.com/CUNY-CL/yoyodyne/pull/74 and it worked? Either my memory is wrong or maybe we have a regression?

**Comment by kylebgorman** [comment]
I actually didn't test it---we jsut have a TODO that says it's not working:

https://github.com/kylebgorman/yoyodyne/blob/61fbb9a085d081c64736343cdb51225765f736cc/yoyodyne/predict.py#L53

If it is working then we should revert this and remove that TODO.

**Comment by Adamits** [comment]
Ah, I should have removed that TODO then! I can test to be sure.

**Comment by kylebgorman** [comment]
Closing in favor of #97.

**Pull request closed without merging**
